/**
 * iOS Home Screen launch images.
 *
 * Without these, an installed app opens on a blank white rectangle until React paints — the single
 * most "this is just a website" moment in the whole experience. iOS only uses an image whose media
 * query matches the device exactly, hence one entry per screen size and pixel ratio, in the app's
 * own paper and ink so the launch screen dissolves into the first frame.
 *
 * Light entries come first: iOS takes the LAST matching link, so the dark-scheme ones must follow
 * to win when the device is in dark mode.
 *
 * Generated by scripts/generate-splash.mjs — do not edit by hand.
 */
export const APPLE_LAUNCH_IMAGES: { media: string; href: string }[] = [
  { media: "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)", href: "/splash/splash-440x956@3x-light.png" },
  { media: "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)", href: "/splash/splash-430x932@3x-light.png" },
  { media: "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)", href: "/splash/splash-428x926@3x-light.png" },
  { media: "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)", href: "/splash/splash-402x874@3x-light.png" },
  { media: "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)", href: "/splash/splash-393x852@3x-light.png" },
  { media: "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)", href: "/splash/splash-390x844@3x-light.png" },
  { media: "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)", href: "/splash/splash-375x812@3x-light.png" },
  { media: "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)", href: "/splash/splash-414x896@3x-light.png" },
  { media: "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)", href: "/splash/splash-414x896@2x-light.png" },
  { media: "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)", href: "/splash/splash-375x667@2x-light.png" },
  { media: "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)", href: "/splash/splash-440x956@3x-dark.png" },
  { media: "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)", href: "/splash/splash-430x932@3x-dark.png" },
  { media: "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)", href: "/splash/splash-428x926@3x-dark.png" },
  { media: "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)", href: "/splash/splash-402x874@3x-dark.png" },
  { media: "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)", href: "/splash/splash-393x852@3x-dark.png" },
  { media: "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)", href: "/splash/splash-390x844@3x-dark.png" },
  { media: "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)", href: "/splash/splash-375x812@3x-dark.png" },
  { media: "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)", href: "/splash/splash-414x896@3x-dark.png" },
  { media: "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)", href: "/splash/splash-414x896@2x-dark.png" },
  { media: "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)", href: "/splash/splash-375x667@2x-dark.png" },
];
