/**
 * Regenerates the iOS Home Screen launch images and the module listing them.
 *
 * Run after changing the mark or the paper/ink palette:
 *   npm run generate:splash
 *
 * sharp is not a project dependency — it is needed only to author these assets, which are
 * committed — so install it on demand: `npm i --no-save sharp && npm run generate:splash`.
 */
import sharp from "sharp";
import { mkdirSync, writeFileSync } from "node:fs";

const HEADER = `/**
 * iOS Home Screen launch images.
 *
 * Without these, an installed app opens on a blank white rectangle until React paints — the single
 * most "this is just a website" moment in the whole experience. iOS only uses an image whose media
 * query matches the device exactly, hence one entry per screen size and pixel ratio, in the app's
 * own paper and ink so the launch screen dissolves into the first frame.
 *
 * Light entries come first: iOS takes the LAST matching link, so the dark-scheme ones must follow
 * to win when the device is in dark mode.
 *
 * Generated by scripts/generate-splash.mjs — do not edit by hand.
 */
`;

const OUT = new URL("../public/splash", import.meta.url).pathname;
mkdirSync(OUT, { recursive: true });

// Current and recent iPhones, as CSS pt size + device pixel ratio. Portrait only: the manifest
// locks orientation, and iOS only consults a matching startup image.
const DEVICES = [
  { w: 440, h: 956, r: 3 }, // iPhone 16 Pro Max
  { w: 430, h: 932, r: 3 }, // 15/16 Plus, 14/15 Pro Max
  { w: 428, h: 926, r: 3 }, // 12/13/14 Pro Max
  { w: 402, h: 874, r: 3 }, // iPhone 16 Pro
  { w: 393, h: 852, r: 3 }, // 14 Pro, 15/16
  { w: 390, h: 844, r: 3 }, // 12/13/14
  { w: 375, h: 812, r: 3 }, // X, XS, 11 Pro, 12/13 mini
  { w: 414, h: 896, r: 3 }, // XS Max, 11 Pro Max
  { w: 414, h: 896, r: 2 }, // XR, 11
  { w: 375, h: 667, r: 2 }, // SE 2nd/3rd gen
];

// Matches the app's own paper/ink tokens so the launch screen dissolves into the first frame.
const SCHEMES = [
  { name: "light", bg: "#FBFAF7", mark: "#0F6E56", dark: false },
  { name: "dark", bg: "#151311", mark: "#9FE1CB", dark: true },
];

const links = [];

for (const { w, h, r } of DEVICES) {
  for (const { name, bg, mark, dark } of SCHEMES) {
    const pw = w * r;
    const ph = h * r;
    // The mark is drawn at a fixed fraction of the shorter edge so it reads the same on every size.
    const s = Math.round(Math.min(pw, ph) * 0.22);
    const cx = pw / 2;
    const cy = ph / 2;

    const svg = Buffer.from(
      `<svg xmlns="http://www.w3.org/2000/svg" width="${pw}" height="${ph}" viewBox="0 0 ${pw} ${ph}">
        <rect width="${pw}" height="${ph}" fill="${bg}"/>
        <g transform="translate(${cx - s / 2} ${cy - s / 2}) scale(${s / 100})">
          <path d="M50 4C36 24 22 34 22 54a28 28 0 0 0 56 0C78 34 64 24 50 4z"
                fill="none" stroke="${mark}" stroke-width="7" stroke-linejoin="round"/>
        </g>
      </svg>`,
    );

    const file = `splash-${w}x${h}@${r}x-${name}.png`;
    await sharp(svg).png({ compressionLevel: 9, palette: true }).toFile(`${OUT}/${file}`);

    const media =
      `(device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${r})` +
      ` and (orientation: portrait)` +
      (dark ? ` and (prefers-color-scheme: dark)` : ``);
    links.push({ media, href: `/splash/${file}`, dark });
  }
}

// Light entries must come first: iOS takes the last matching link, so the dark-scheme ones need to
// win when the scheme matches.
links.sort((a, b) => Number(a.dark) - Number(b.dark));
const rows = links.map((l) => `  { media: ${JSON.stringify(l.media)}, href: ${JSON.stringify(l.href)} },`).join("\n");
writeFileSync(
  new URL("../src/app/appleLaunchImages.ts", import.meta.url).pathname,
  `${HEADER}export const APPLE_LAUNCH_IMAGES: { media: string; href: string }[] = [\n${rows}\n];\n`,
);
console.log(`${links.length} launch images`);
